data:
  train_bs: 1 # 12
  train_width: 512
  train_height: 512 
  meta_paths:
    - "data/thuman2_ortho_6_meta.json"
    - "data/customhumans_ortho_6_meta.json"
  n_sample_frames: 20 # 只用于中间log的时候

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True 
  gradient_checkpointing: False 
  max_train_steps: 60000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: False
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 1 # 2000


vae_model_path: "/apdcephfs_cq10/share_1330077/hexu/SVD_Xtend/stable-video-diffusion-img2vid-xt/vae"

weight_dtype: 'fp16'  # [fp16, fp32]


seed: 224116
# resume_from_checkpoint: "latest"
resume_from_checkpoint: ""
checkpointing_steps: 4000
# checkpointing_steps: 1
save_model_epoch_interval: 20 # 50epoch大约是3750iter 1epoch 75iter (bs=10*8时)
# save_model_epoch_interval: 1
exp_name: 'vae'
output_dir: '/apdcephfs_cq10/share_1330077/hexu/NVS/nvs_dual_branch'  