pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
base_model_path: './pretrained_weights/sd-image-variations-diffusers'
denoising_unet_path: "/apdcephfs_cq10/share_1330077/hexu/NVS/exp_output/stage1_36frame_wo_depth/denoising_unet-30000.pth"
reference_unet_path: "/apdcephfs_cq10/share_1330077/hexu/NVS/exp_output/stage1_36frame_wo_depth/reference_unet-30000.pth"
normal_guider_path: "/apdcephfs_cq10/share_1330077/hexu/NVS/exp_output/stage1_36frame_wo_depth/normal_guider-30000.pth"
depth_guider_path: "/apdcephfs_cq10/share_1330077/hexu/NVS/exp_output/stage1_36frame_wo_depth/depth_guider-30000.pth"

use_normal_guider: True
use_depth_guider: False

weight_dtype: 'fp16'

clip_length: 32

exp_name: 'stage1_36frame_wo_depth'
output_dir: '/apdcephfs_cq10/share_1330077/hexu/NVS/exp_output'  

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "scaled_linear"
  clip_sample: false
  steps_offset: 1
  ### Zero-SNR params
  prediction_type: "v_prediction"
  rescale_betas_zero_snr: True
  timestep_spacing: "trailing"

test_cases:
  "./configs/inference/ref_images/anyone-2.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4" 
    - "./configs/inference/pose_videos/anyone-video-5_kps.mp4"
  "./configs/inference/ref_images/anyone-10.png":
    - "./configs/inference/pose_videos/anyone-video-1_kps.mp4"
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
  "./configs/inference/ref_images/anyone-11.png":
    - "./configs/inference/pose_videos/anyone-video-1_kps.mp4"
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
  "./configs/inference/ref_images/anyone-3.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
    - "./configs/inference/pose_videos/anyone-video-5_kps.mp4"
  "./configs/inference/ref_images/anyone-5.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4" 
